name: Update

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # build in alpine chroot to allow for the binary to be static
    - run: wget -O rootfs.tgz https://dl-cdn.alpinelinux.org/alpine/v3.18/releases/x86_64/alpine-minirootfs-3.18.3-x86_64.tar.gz
    - run: mkdir rootfs
    - run: sudo tar -C rootfs -xf rootfs.tgz
    - run: sudo cp static.sh rootfs/
    # actually have DNS resolution
    - run: printf 'nameserver 1.1.1.1\n' | sudo tee rootfs/etc/resolv.conf
    # git wants urandom
    - run: sudo mount -t devtmpfs devtmpfs rootfs/dev/
    - run: sudo chroot rootfs /static.sh

    - run: mkdir a
    - run: cp rootfs/porttest/server/server rootfs/porttest/client/client a
    - run: cd a && zip release.zip server client && mv release.zip ..

    - uses: actions/create-release@v1
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: release.zip
        asset_name: release.zip
        asset_content_type: application/zip
